version: '3.8'

services:
  database:
    image: postgres:13.3
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5434:5432'
  php:
    container_name: php
    build:
      context: infra/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/symfony_docker
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/symfony_docker
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

volumes:
    postgres_data:
        driver: local